apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qspill-controller
  labels:
    app.kubernetes.io/name: qspill-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qspill-controller
subjects:
  - kind: ServiceAccount
    name: qspill-controller
    namespace: qspill-controller-system
