//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveSpillTarget) DeepCopyInto(out *ActiveSpillTarget) {
	*out = *in
	if in.SpilledCapacity != nil {
		in, out := &in.SpilledCapacity, &out.SpilledCapacity
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	in.SpillStartTime.DeepCopyInto(&out.SpillStartTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveSpillTarget.
func (in *ActiveSpillTarget) DeepCopy() *ActiveSpillTarget {
	if in == nil {
		return nil
	}
	out := new(ActiveSpillTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QSpillPolicy) DeepCopyInto(out *QSpillPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QSpillPolicy.
func (in *QSpillPolicy) DeepCopy() *QSpillPolicy {
	if in == nil {
		return nil
	}
	out := new(QSpillPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QSpillPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QSpillPolicyList) DeepCopyInto(out *QSpillPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QSpillPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QSpillPolicyList.
func (in *QSpillPolicyList) DeepCopy() *QSpillPolicyList {
	if in == nil {
		return nil
	}
	out := new(QSpillPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QSpillPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QSpillPolicySpec) DeepCopyInto(out *QSpillPolicySpec) {
	*out = *in
	out.SpillTrigger = in.SpillTrigger
	if in.SpillTargets != nil {
		in, out := &in.SpillTargets, &out.SpillTargets
		*out = make([]SpillTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReclaimPolicy != nil {
		in, out := &in.ReclaimPolicy, &out.ReclaimPolicy
		*out = new(ReclaimPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QSpillPolicySpec.
func (in *QSpillPolicySpec) DeepCopy() *QSpillPolicySpec {
	if in == nil {
		return nil
	}
	out := new(QSpillPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QSpillPolicyStatus) DeepCopyInto(out *QSpillPolicyStatus) {
	*out = *in
	if in.CurrentSpillTargets != nil {
		in, out := &in.CurrentSpillTargets, &out.CurrentSpillTargets
		*out = make([]ActiveSpillTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QSpillPolicyStatus.
func (in *QSpillPolicyStatus) DeepCopy() *QSpillPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(QSpillPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReclaimPolicy) DeepCopyInto(out *ReclaimPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReclaimPolicy.
func (in *ReclaimPolicy) DeepCopy() *ReclaimPolicy {
	if in == nil {
		return nil
	}
	out := new(ReclaimPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpillTarget) DeepCopyInto(out *SpillTarget) {
	*out = *in
	if in.MaxSpillCapacity != nil {
		in, out := &in.MaxSpillCapacity, &out.MaxSpillCapacity
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpillTarget.
func (in *SpillTarget) DeepCopy() *SpillTarget {
	if in == nil {
		return nil
	}
	out := new(SpillTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpillTrigger) DeepCopyInto(out *SpillTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpillTrigger.
func (in *SpillTrigger) DeepCopy() *SpillTrigger {
	if in == nil {
		return nil
	}
	out := new(SpillTrigger)
	in.DeepCopyInto(out)
	return out
}
